INSERT INTO `encheres`.`categories`(`libelle`)VALUES("Voitures");
INSERT INTO `encheres`.`categories`(`libelle`)VALUES("Motos");
INSERT INTO `encheres`.`categories`(`libelle`)VALUES("Caravaning");
INSERT INTO `encheres`.`categories`(`libelle`)VALUES("Utilitaires");
INSERT INTO `encheres`.`categories`(`libelle`)VALUES("Equipement Auto");
INSERT INTO `encheres`.`categories`(`libelle`)VALUES("Nautisme");
INSERT INTO `encheres`.`categories`(`libelle`)VALUES("Ventes immobilières");
INSERT INTO `encheres`.`categories`(`libelle`)VALUES("Locations");
INSERT INTO `encheres`.`categories`(`libelle`)VALUES("Colocations");
INSERT INTO `encheres`.`categories`(`libelle`)VALUES("Locations & Gîtes");
INSERT INTO `encheres`.`categories`(`libelle`)VALUES("Bureaux & Commerces");
INSERT INTO `encheres`.`categories`(`libelle`)VALUES("Informatique");
INSERT INTO `encheres`.`categories`(`libelle`)VALUES("Image & Son");
INSERT INTO `encheres`.`categories`(`libelle`)VALUES("Téléphonie");
INSERT INTO `encheres`.`categories`(`libelle`)VALUES("Ameublement");
INSERT INTO `encheres`.`categories`(`libelle`)VALUES("Electroménager");
INSERT INTO `encheres`.`categories`(`libelle`)VALUES("Bricolage");
INSERT INTO `encheres`.`categories`(`libelle`)VALUES("Vêtements");
INSERT INTO `encheres`.`categories`(`libelle`)VALUES("Equipement bébé");
INSERT INTO `encheres`.`categories`(`libelle`)VALUES("DVD / Films");
INSERT INTO `encheres`.`categories`(`libelle`)VALUES("CD / Musique");
INSERT INTO `encheres`.`categories`(`libelle`)VALUES("Livres");
INSERT INTO `encheres`.`categories`(`libelle`)VALUES("Animaux");
INSERT INTO `encheres`.`categories`(`libelle`)VALUES("Sports & Hobbies");
INSERT INTO `encheres`.`categories`(`libelle`)VALUES("Instruments de musique");
INSERT INTO `encheres`.`categories`(`libelle`)VALUES("Équipements Industriels");
INSERT INTO `encheres`.`categories`(`libelle`)VALUES("Offres d'emploi");
INSERT INTO `encheres`.`categories`(`libelle`)VALUES("Prestations de services");
INSERT INTO `encheres`.`categories`(`libelle`)VALUES("Billetterie");
INSERT INTO `encheres`.`categories`(`libelle`)VALUES("Cours particuliers");
INSERT INTO `encheres`.`categories`(`libelle`)VALUES("Autres");
INSERT INTO `encheres`.`categories`(`libelle`)VALUES("Décoration");
INSERT INTO `encheres`.`categories`(`libelle`)VALUES("Collection");
INSERT INTO `encheres`.`categories`(`libelle`)VALUES("Jeux & Jouets");
INSERT INTO `encheres`.`categories`(`libelle`)VALUES("Montres & Bijoux");
INSERT INTO `encheres`.`categories`(`libelle`)VALUES("Consoles & Jeux vidéo");
INSERT INTO `encheres`.`categories`(`libelle`)VALUES("Equipement Moto");
INSERT INTO `encheres`.`categories`(`libelle`)VALUES("Arts de la table");
INSERT INTO `encheres`.`categories`(`libelle`)VALUES("Linge de maison");
INSERT INTO `encheres`.`categories`(`libelle`)VALUES("Accessoires & Bagagerie");
INSERT INTO `encheres`.`categories`(`libelle`)VALUES("Vins & Gastronomie");
INSERT INTO `encheres`.`categories`(`libelle`)VALUES("Evénements");
INSERT INTO `encheres`.`categories`(`libelle`)VALUES("Equipement Caravaning");
INSERT INTO `encheres`.`categories`(`libelle`)VALUES("Equipement Nautisme");
INSERT INTO `encheres`.`categories`(`libelle`)VALUES("Jardinage");
INSERT INTO `encheres`.`categories`(`libelle`)VALUES("Chaussures");
INSERT INTO `encheres`.`categories`(`libelle`)VALUES("Vêtements bébé");
INSERT INTO `encheres`.`categories`(`libelle`)VALUES("Vélos");
INSERT INTO `encheres`.`categories`(`libelle`)VALUES("Matériel Agricole");
INSERT INTO `encheres`.`categories`(`libelle`)VALUES("Transport - Manutention");
INSERT INTO `encheres`.`categories`(`libelle`)VALUES("BTP - Chantier Gros-oeuvre");
INSERT INTO `encheres`.`categories`(`libelle`)VALUES("Outillage - Matériaux");
INSERT INTO `encheres`.`categories`(`libelle`)VALUES("Restauration - Hôtellerie");
INSERT INTO `encheres`.`categories`(`libelle`)VALUES("Fournitures de Bureau");
INSERT INTO `encheres`.`categories`(`libelle`)VALUES("Commerces & Marchés");
INSERT INTO `encheres`.`categories`(`libelle`)VALUES("Matériel Médical");
INSERT INTO `encheres`.`categories`(`libelle`)VALUES("Covoiturage");
INSERT INTO `encheres`.`categories`(`libelle`)VALUES("Chambres d'hôtes");
INSERT INTO `encheres`.`categories`(`libelle`)VALUES("Campings");
INSERT INTO `encheres`.`categories`(`libelle`)VALUES("Hôtels");
INSERT INTO `encheres`.`categories`(`libelle`)VALUES("Hébergements insolites");